### ISSUE TITLE
Compare Sets Appyter crushes when attempting to processed the attached file

### ISSUE THREAD

**Issue by AviMaayan** [MaayanLab/appyter-catalog#883] opened 2023-03-13 02:51 UTC
[nfat-gmt.txt](https://github.com/MaayanLab/appyter-catalog/files/10953063/nfat-gmt.txt)

**Comment by AviMaayan** [comment] 2023-03-13 02:51
[nfat-gmt.txt](https://github.com/MaayanLab/appyter-catalog/files/10953067/nfat-gmt.txt)

**Comment by u8sand** [comment] 2023-03-13 19:53
Duplicate of #719 -- appyter currently supports at most 6 sets

**Closed by u8sand** 2023-03-13 19:53 UTC

**Comment by u8sand** [comment] 2023-03-13 19:56
Additionally, the attached GMT looks like it may be malformed. The "first" gene might get lost if they're in the "description" field. Otherwise, if it's indeed a description then it'll be fine.
